name: "Docker run"

on:
  push:
    branches: [ main ]

jobs: 
  build: 
    runs-on: self-hosted
    
    strategy:
      matrix:
        python-version: ['3.x', '2.x']

    name: Python ${{ matrix.python-version }}
    steps: 
      - 
        uses: actions/checkout@v3
      -
        name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      -
        name: "Check python --version"
        run: |
            python --version
      - 
        name: "Build the Docker image"
        run: |
            echo "${{ secrets.SUDO_PASS }}" | sudo -S chmod 666 /var/run/docker.sock
            echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
            docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
            docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
            # docker run docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
      - 
        name: "Run the Docker image"
        run: |
            docker run docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:$GITHUB_SHA
